/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Raghav Gupta (https://sketchfab.com/raghav-wd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pikachu-37c740f674cd4719a1d1d2970bbe8c30
Title: Pikachu
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useEffect, useRef } from 'react';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    GLTF_created_0_rootJoint: THREE.SkinnedMesh;
    Object_7: THREE.SkinnedMesh;
    Object_8: THREE.SkinnedMesh;
    Object_9: THREE.SkinnedMesh;
    Object_10: THREE.SkinnedMesh;
    Object_11: THREE.SkinnedMesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;

    Material_160: THREE.MeshStandardMaterial;
    'Material.001': THREE.MeshStandardMaterial;
    'Material.003': THREE.MeshStandardMaterial;
    'Material.002': THREE.MeshStandardMaterial;
  };
};

interface PikachuProps {
  scale?: THREE.Vector3;
  position?: THREE.Vector3;
  rotation?: THREE.Euler;
  currentAnimation: string;
}

const Pikachu: React.FC<PikachuProps> = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    '/3d/pikachu.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => {
      action?.stop();
    });

    if (actions[currentAnimation]) actions[currentAnimation]?.play();
  }, [actions, currentAnimation]);

  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0.006, -0.018, -0.048]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Pikachu_49"
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.05}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Material_160}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials['Material.001']}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials['Material.003']}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials['Material.002']}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <group name="PikachuM_48" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Pikachu;
